apiVersion: v1
kind: Service
metadata:
 name: capsnet-fashion-svc
 labels:
  app: capsnet-fashion
spec:
 type: NodePort
 ports:
 - port: 5000
   nodePort: 30085
   protocol: TCP
 selector:
   app: capsnet-fashion